version: '3.9'
services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: v0.47.1  # Replace with your desired Metabase version
        MB_EDITION: oss  # Replace with your desired edition (oss or pro)
    image: appeq_metabase:latest
    container_name: appeq_metabase
    ports:
      - "3000:3000"  # Expose port 3050 for Metabase
    volumes:
      - ./metabase-data:/metabase-data
      - ./metabase-data/plugins:/metabase-data/plugins
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data
      MB_IS_METABOT_ENABLED: "true" # Absolute path to plugins
    restart: unless-stopped






